name: SQL Autograding

on:
  push:
  pull_request:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Start MySQL
        run: |
          sudo systemctl start mysql

      - name: Execute Student SQL
        run: |
          mysql -u root < starter.sql

      - name: Execute Test Cases
        run: |
          mysql -u root < testcase.sql
